version: '2'

services:
  # Based on https://realpython.com/blog/python/django-development-with-docker-compose-and-machine/
  # If restart: always is enabled it will run even if the machine is restarted.
  # Docker container ports do not interfere with the host ports

  {{ project_name }}_postgis:
    restart: always
    image: mdillon/postgis:9.5
    volumes:
      - {{ project_name }}_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"

  {{ project_name }}_redis:
    restart: always
    image: redis:3.0.7

  {{ project_name }}_web:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/staging/Dockerfile
    command: /gunicorn.sh
    volumes:
      - ./media:/code/media
      - ./staticfiles:/code/staticfiles
      - ./{{ project_name }}_management:/code/{{ project_name }}_management
    depends_on:
      - {{ project_name }}_postgis
      - {{ project_name }}_redis
    env_file: .env

  {{ project_name }}_nginx:
    restart: always
    build: ./compose/nginx/staging
    depends_on:
      - {{ project_name }}_web
    volumes_from:
      - {{ project_name }}_web
      - {{ project_name }}_certbot
    ports:
      - "0.0.0.0:8005:80"

  {{ project_name }}_certbot:
    restart: always
    build: ./compose/certbot/staging
    volumes:
      - {{ project_name }}_staging_certs:/etc/letsencrypt
    volumes_from:
      - {{ project_name }}_web
    depends_on:
      - {{ project_name }}_nginx
      - {{ project_name }}_web
    env_file: staging.env

volumes:
  {{ project_name }}_data:
  {{ project_name }}_staging_certs:
